### home
GET {{host}}/ HTTP/1.1
content-type: application/json

{}


### User
GET {{host}}/user HTTP/1.1
content-type: application/json

{
  "userAuth": {
    "userToken": "{{userToken}}"
  }
}

### OAuth
GET {{host}}/oauth/authorize?callbackURL=https%3A%2F%2Fsample-driver.rokid.com%2Foauth-callback%3FdriverId%3Ddriver-mimic HTTP/1.1
