### Get
POST {{host}}/driver/get HTTP/1.1
content-type: application/json

{
  "device": {
    "deviceId": "1",
    "userAuth": {
      "userToken": "{{userToken}}"
    }
  }
}

### List
POST {{host}}/driver/list HTTP/1.1
content-type: application/json

{
  "userAuth": {
    "userToken": "{{userToken}}"
  }
}

### Execute
POST {{host}}/driver/execute HTTP/1.1
content-type: application/json

{
  "device": {
    "deviceId": "1",
    "deviceInfo": {
      "foo": "bar",
      "from": "sample-driver",
      "type": "ac"
    },
    "userAuth": {
      "userToken": "{{userToken}}"
    }
  },
  "action": {
    "property": "switch",
    "name": "on"
  }
}


### Command OAuth
POST {{host}}/driver/command HTTP/1.1
content-type: application/json

{
  "command": "OAuth",
  "params": {
    "callbackURL": "{{host}}/oauth-callback?driverId=driver-mimic"
  }
}

### Command OAuthRefresh
POST {{host}}/driver/command HTTP/1.1
content-type: application/json

{
  "command": "OAuthRefresh",
  "params": {
    "userId" : "paw-foo",
    "userToken" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImZvbyIsImlhdCI6MTUwOTM2NjYzMCwiZXhwIjoxNTA5MzY3ODMwfQ.7f4sUtogtjsLSP4HmThWtxZXRJ9nuuQmGwlLe-UyUbI",
    "expiredTime" : "1509360749",
    "expiresIn" : 1200
  }
}


### Command Login
POST {{host}}/driver/command HTTP/1.1
content-type: application/json

{
  "command": "Login",
  "params": {
    "username": "{{username}}",
    "password": "{{password}}"
  }
}
